
/**************************************************************
 *	
 *	EnemySlain, 8 bit, 11025Hz,
 *	1 channel, 33984 bytes/channel
 *	Total Size: 1 * 33984 + 4 (header) = 34028 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Kananx/Documents/CS2261/HWs/KananPatel_FinalProject/audio/EnemySlain.wav
 *	Time-stamp: Thu Dec 01 13:49:40 2016
 *	
 **************************************************************/

#ifndef __ENEMYSLAINH__
#define __ENEMYSLAINH__

#define ENEMYSLAINFREQ 11025
#define ENEMYSLAINLEN 33984

extern const unsigned char EnemySlain[33984];

#endif /* __ENEMYSLAINH__ */
