
/**************************************************************
 *	
 *	gamemusic, 8 bit, 11025Hz,
 *	1 channel, 794304 bytes/channel
 *	Total Size: 1 * 794304 + 4 (header) = 794348 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Kananx/Documents/CS2261/HWs/KananPatel_FinalProject/audio/gamemusic.wav
 *	Time-stamp: Tue Dec 06 14:30:41 2016
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 794304

extern const unsigned char gamemusic[794304];

#endif /* __GAMEMUSICH__ */
