
/**************************************************************
 *	
 *	Defeat, 8 bit, 11025Hz,
 *	1 channel, 18144 bytes/channel
 *	Total Size: 1 * 18144 + 4 (header) = 18188 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Kananx/Documents/CS2261/HWs/KananPatel_FinalProject/audio/Defeat.wav
 *	Time-stamp: Thu Dec 01 14:39:45 2016
 *	
 **************************************************************/

#ifndef __DEFEATH__
#define __DEFEATH__

#define DEFEATFREQ 11025
#define DEFEATLEN 18144

extern const unsigned char Defeat[18144];

#endif /* __DEFEATH__ */
