
/**************************************************************
 *	
 *	LoginScreenLoop, 8 bit, 11025Hz,
 *	1 channel, 1835530 bytes/channel
 *	Total Size: 1 * 1835530 + 4 (header) = 1835574 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Kananx/Documents/CS2261/HWs/KananPatel_FinalProject/audio/LoginScreenLoop.wav
 *	Time-stamp: Thu Dec 01 13:57:49 2016
 *	
 **************************************************************/

#ifndef __LOGINSCREENLOOPH__
#define __LOGINSCREENLOOPH__

#define LOGINSCREENLOOPFREQ 11025
#define LOGINSCREENLOOPLEN 1835530

extern const unsigned char LoginScreenLoop[1835530];

#endif /* __LOGINSCREENLOOPH__ */
