
/**************************************************************
 *	
 *	Victory, 8 bit, 11025Hz,
 *	1 channel, 19584 bytes/channel
 *	Total Size: 1 * 19584 + 4 (header) = 19628 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Kananx/Documents/CS2261/HWs/KananPatel_FinalProject/audio/Victory.wav
 *	Time-stamp: Thu Dec 01 14:29:07 2016
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 19584

extern const unsigned char Victory[19584];

#endif /* __VICTORYH__ */
